### ISSUE TITLE
mb_strlen() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by hamza-mostafa** [pvtl/voyager-forms#2]
Hi guys,
I got this issue with the filed data, it passes array as it collects array, however the browse table is expecting string.

voyager BREAD browse:`
browse.blade.php`
```@elseif($row->type == 'text')
@include('voyager::multilingual.input-hidden-bread-browse')
<div class="readmore">{{ mb_strlen( $data->{$row->field} ) > 200 ? mb_substr($data->{$row->field}, 0, 200) . ' ...' : $data->{$row->field} }}</div>
```

reproducing the error:
used the out of the box form on the frontend .. then I went to enquiries .. both ways are having the same issue .. from the admin menu and from inside the form 'view enquiries'

I made a work around for that, but fragile 
`project/resources/views/vendor/voyager/enquiries/browse.blade.php`
```@include('voyager::multilingual.input-hidden-bread-browse')
@if($row->field == 'data')
<div class="readmore">{{  implode(", ", $data->{$row->field}) }}</div>
@else
<div class="readmore">{{ mb_strlen( $data->{$row->field} ) > 200 ? mb_substr($data->{$row->field}, 0, 200) . ' ...' : $data->{$row->field} }}</div>
@endif
```

**Comment by Jean-PierreGassin** [comment]
Hey @hamza-mostafa,

Firstly I want to say thanks for picking this up and giving us a rundown on how you came across it, doing this really helps.

I've been able to replicate the issue and have patched it along with another issue I came across during testing, you can find my changes in these commits [#1](https://github.com/pvtl/voyager-forms/commit/14143f1ae8852dbddeef134ac80b95676101feed), [#2](https://github.com/pvtl/voyager-forms/commit/d2b4cd49737a16502aebed7d6ab0844a0aa963e8),  [#3](https://github.com/pvtl/voyager-forms/commit/83e2993a55b9184664e10f74ed34606644aa603f).

For you to get this working however I'd suggest you do the following:
* In your database, navigate to the `data_rows` table
* Find the row with its `field =  data` and `type = text` for the `data_type_id = id_of_forms_data_type` (the `data_type_id` for me is 13)
* Remove this row from `data_rows`

The reasoning behind this is because Voyager's BREAD browse template expects all displayable row data to be a certain type depending on the type provided in the database for that row - in this case it's set to `text` and there are no types that support arrays (which is what this data field contains once it's unserialized).

Happy to review any pull requests regarding the issue, however our main goal here is to not display the `data` field in the BREAD browse template in the first place as that data should only be viewable in a single enquiries view.

**Comment by hamza-mostafa** [comment]
easier and better solution :)
Thanks @Jean-PierreGassin

**Comment by mallardduck** [comment]
@Jean-PierreGassin sorry to revive a dead issue here - I think there's a flaw in the way #2 addressed the issue here. I have a project that is new (creating it now) that encountered this issue.

I believe it happened because I edited the Bread options for the Enquiry data type. The best I can reason is that upon editing the "Display Column Name" for columns on that Bread forced defaults on the data row as it didn't exist. So the current solution that simply doesn't create an entry for the data column isn't sufficient, otherwise users may experience what I've encountered.
